# config.yaml
server:
  port: 9999

mysql:
  host: db.cfsingle.fun
  port: 3306
  username: zanso
  password: 4HjZRnQH0O
  db: db_zanso

redis:
  host: redis.cfsingle.fun
  password: redisPwd@123!
  port: 6379
  database: 0

storage:
  provider: minio
  local_dir: ./uploads
  public_base_url: ""

minio:
  endpoint: http://minio.cfsingle.fun:9000
  accessKey: singleminio
  secretKey: singelminio123
  bucket: single0
  downloadBase: http://ik.aaxx.uk/getFile/

share:
  base_url: ""

auth:
  session_ttl_hours: 168
