# config.yaml
server:
  port: 8888

mysql:
  host: db.cfsingle.fun
  port: 3306
  username: zanso
  password: 4HjZRnQH0O
  db: db_zanso

redis:
  host: redis.cfsingle.fun
  password: redisPwd@123!
  port: 6379
  database: 0

storage:
  local_dir: ./uploads
  public_base_url: ""

minio:
  enabled: false
  endpoint: "min00"
  access_key: "singleminio"
  secret_key: "singelminio123"
  bucket: single0
  secure: false
  region: ""
  auto_create_bucket: true
  public_base_url: ""

share:
  base_url: ""

auth:
  session_ttl_hours: 168
