# config.yaml
server:
  port: 8888

mysql:
  host: db.cle.fun
  port: 3306
  username: dbdata
  password: dbdata@12we34
  db: db_data

redis:
  host: redis.cfsingle.fun
  password: redisPwd@123!
  port: 6379
  database: 0
